name: Publish Plugin Template

on:
  workflow_call:
    inputs:
      plugin-name:
        required: true
        type: string
      version-type:
        required: false
        type: string
        default: 'patch'
        description: 'Version type to bump: patch, minor, major'
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/${{ inputs.plugin-name }}

    permissions:
      contents: write # Needed for pushing commits
      packages: write # Needed for publishing to NPM

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for commits and tags

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: |
          cd ../..
          pnpm install

      - name: Build plugin
        run: pnpm run build

      - name: Bump version
        id: bump
        run: |
          echo "Current version: $(pnpm pkg get version)"
          # Bump the version automatically using pnpm's semver support
          new_version=$(pnpm version ${{ inputs.version-type }} --no-git-tag-version | tr -d '"')
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json
          git commit -m "chore: bump version to ${{ steps.bump.outputs.new_version }}" || echo "No changes to commit"
          # Push using GITHUB_TOKEN in URL for authentication
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "@flexiweb:registry=https://registry.npmjs.org/" >> ~/.npmrc
          pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
